import { Product } from '../contexts/CartContext';

// Mock products data for local development when Edge Function is not deployed
export const mockProducts: Product[] = [
  // China Store - Traditional medicines
  {
    id: '1',
    name: '云南白药',
    name_en: 'Yunnan Baiyao',
    name_vi: 'Vân Nam Bạch Dược',
    name_zh: '云南白药',
    description: 'Традиционное китайское средство для остановки кровотечений и заживления ран',
    description_en: 'Traditional Chinese medicine for stopping bleeding and wound healing',
    description_vi: 'Thuốc cổ truyền Trung Quốc để cầm máu và chữa lành vết thương',
    description_zh: '传统中药止血愈伤药',
    composition: 'Корень белой травы, камфора, экстракты трав',
    composition_en: 'White herb root, camphor, herbal extracts',
    composition_vi: 'Rễ cỏ trắng, long não, chiết xuất thảo dược',
    composition_zh: '白药根、樟脑、草药提取物',
    usage: 'Наносить на пораженную область 2-3 раза в день',
    usage_en: 'Apply to affected area 2-3 times daily',
    usage_vi: 'Bôi lên vùng bị ảnh hưởng 2-3 lần mỗi ngày',
    usage_zh: '每天涂抹患处2-3次',
    price: 850,
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
    category: 'herbal_medicine',
    disease: 'wounds',
    store: 'china',
    inStock: true,
    weight: 0.1,
    isSample: false
  },
  {
    id: '2',
    name: 'Жемчужный крем',
    name_en: 'Pearl Cream',
    name_vi: 'Kem Ngọc Trai',
    name_zh: '珍珠膏',
    description: 'Увлажняющий крем с жемчужной пудрой для здоровой кожи',
    description_en: 'Moisturizing cream with pearl powder for healthy skin',
    description_vi: 'Kem dưỡng ẩm với bột ngọc trai cho làn da khỏe mạnh',
    description_zh: '含珍珠粉的保湿霜',
    composition: 'Жемчужная пудра, коллаген, витамин E',
    composition_en: 'Pearl powder, collagen, vitamin E',
    composition_vi: 'Bột ngọc trai, collagen, vitamin E',
    composition_zh: '珍珠粉、胶原蛋白、维生素E',
    usage: 'Наносить на чистую кожу лица утром и вечером',
    usage_en: 'Apply to clean facial skin morning and evening',
    usage_vi: 'Thoa lên da mặt sạch buổi sáng và tối',
    usage_zh: '早晚涂抹于洁净面部',
    price: 1200,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400',
    category: 'cosmetics',
    disease: 'skin_care',
    store: 'china',
    inStock: true,
    weight: 0.15,
    isSample: false
  },
  {
    id: '3',
    name: 'Женьшень красный',
    name_en: 'Red Ginseng',
    name_vi: 'Nhân Sâm Đỏ',
    name_zh: '红参',
    description: 'Корень красного женьшеня для повышения энергии и иммунитета',
    description_en: 'Red ginseng root for energy and immunity boost',
    description_vi: 'Rễ nhân sâm đỏ tăng cường năng lượng và miễn dịch',
    description_zh: '红参根增强能量和免疫力',
    composition: 'Корень красного женьшеня 100%',
    composition_en: 'Red ginseng root 100%',
    composition_vi: 'Rễ nhân sâm đỏ 100%',
    composition_zh: '红参根100%',
    usage: 'Принимать 1-2 капсулы в день во время еды',
    usage_en: 'Take 1-2 capsules daily with meals',
    usage_vi: 'Uống 1-2 viên mỗi ngày cùng bữa ăn',
    usage_zh: '每日随餐服用1-2粒',
    price: 3500,
    image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=400',
    category: 'supplements',
    disease: 'immunity',
    store: 'china',
    inStock: true,
    weight: 0.2,
    isSample: false
  },
  {
    id: '4',
    name: 'Бальзам Тигровый',
    name_en: 'Tiger Balm',
    name_vi: 'Cao Hổ',
    name_zh: '虎标万金油',
    description: 'Обезболивающий бальзам при мышечных и суставных болях',
    description_en: 'Pain relief balm for muscle and joint pain',
    description_vi: 'Dầu giảm đau cho đau cơ và khớp',
    description_zh: '缓解肌肉和关节疼痛的药膏',
    composition: 'Камфора, ментол, гвоздичное масло, масло кайепута',
    composition_en: 'Camphor, menthol, clove oil, cajeput oil',
    composition_vi: 'Long não, bạc hà, dầu đinh hương, dầu tràm',
    composition_zh: '樟脑、薄荷醇、丁香油、白千层油',
    usage: 'Втирать в болезненные места 2-3 раза в день',
    usage_en: 'Massage into painful areas 2-3 times daily',
    usage_vi: 'Xoa bóp vào vùng đau 2-3 lần mỗi ngày',
    usage_zh: '每天按摩疼痛部位2-3次',
    price: 450,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400',
    category: 'ointments',
    disease: 'pain',
    store: 'china',
    inStock: true,
    weight: 0.05,
    isSample: false
  },
  {
    id: '5',
    name: 'Пробник - Женьшень',
    name_en: 'Sample - Ginseng',
    name_vi: 'Mẫu thử - Nhân Sâm',
    name_zh: '试用装 - 人参',
    description: 'Пробная упаковка женьшеня (10г)',
    description_en: 'Ginseng sample pack (10g)',
    description_vi: 'Gói mẫu nhân sâm (10g)',
    description_zh: '人参试用装（10克）',
    composition: 'Корень красного женьшеня 100%',
    composition_en: 'Red ginseng root 100%',
    composition_vi: 'Rễ nhân sâm đỏ 100%',
    composition_zh: '红参根100%',
    usage: 'Заварить и пить как чай',
    usage_en: 'Brew and drink as tea',
    usage_vi: 'Pha và uống như trà',
    usage_zh: '冲泡饮用',
    price: 200,
    image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=400',
    category: 'samples',
    disease: 'immunity',
    store: 'china',
    inStock: true,
    weight: 0.01,
    isSample: true
  },

  // Thailand Store - Thai traditional medicines
  {
    id: '11',
    name: 'Тайский бальзам',
    name_en: 'Thai Herbal Balm',
    name_vi: 'Dầu Thảo Dược Thái',
    name_zh: '泰国草药膏',
    description: 'Травяной бальзам для облегчения головной боли и простуды',
    description_en: 'Herbal balm for headache and cold relief',
    description_vi: 'Dầu thảo dược giảm đau đầu và cảm lạnh',
    description_zh: '缓解头痛和感冒的草药膏',
    composition: 'Лемонграсс, эвкалипт, мята, борнеол',
    composition_en: 'Lemongrass, eucalyptus, mint, borneol',
    composition_vi: 'Sả, bạch đàn, bạc hà, borneol',
    composition_zh: '柠檬草、桉树、薄荷、冰片',
    usage: 'Наносить на виски и затылок при головной боли',
    usage_en: 'Apply to temples and back of head for headache',
    usage_vi: 'Thoa lên thái dương và gáy khi đau đầu',
    usage_zh: '头痛时涂抹于太阳穴和后颈',
    price: 380,
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=400',
    category: 'ointments',
    disease: 'headache',
    store: 'thailand',
    inStock: true,
    weight: 0.08,
    isSample: false
  },
  {
    id: '12',
    name: 'Мангостиновая паста',
    name_en: 'Mangosteen Paste',
    name_vi: 'Thuốc Măng Cụt',
    name_zh: '山竹膏',
    description: 'Натуральная паста из мангостина для пищеварения',
    description_en: 'Natural mangosteen paste for digestion',
    description_vi: 'Thuốc dán măng cụt tự nhiên cho tiêu hóa',
    description_zh: '天然山竹膏助消化',
    composition: 'Экстракт мангостина, мед, травы',
    composition_en: 'Mangosteen extract, honey, herbs',
    composition_vi: 'Chiết xuất măng cụt, mật ong, thảo dược',
    composition_zh: '山竹提取物、蜂蜜、草药',
    usage: 'Принимать 1 чайную ложку 3 раза в день',
    usage_en: 'Take 1 teaspoon 3 times daily',
    usage_vi: 'Uống 1 thìa cà phê 3 lần mỗi ngày',
    usage_zh: '每日3次，每次1茶匙',
    price: 650,
    image: 'https://images.unsplash.com/photo-1584308972272-9e4e7685e80f?w=400',
    category: 'herbal_medicine',
    disease: 'digestion',
    store: 'thailand',
    inStock: true,
    weight: 0.12,
    isSample: false
  },
  {
    id: '13',
    name: 'Капсулы из кордицепса',
    name_en: 'Cordyceps Capsules',
    name_vi: 'Viên Đông Trùng Hạ Thảo',
    name_zh: '冬虫夏草胶囊',
    description: 'Капсулы кордицепса для энергии и выносливости',
    description_en: 'Cordyceps capsules for energy and endurance',
    description_vi: 'Viên đông trùng hạ thảo tăng năng lượng',
    description_zh: '冬虫夏草胶囊增强能量',
    composition: 'Экстракт кордицепса 500мг',
    composition_en: 'Cordyceps extract 500mg',
    composition_vi: 'Chiết xuất đông trùng hạ thảo 500mg',
    composition_zh: '冬虫夏草提取物500毫克',
    usage: 'Принимать 2 капсулы в день',
    usage_en: 'Take 2 capsules daily',
    usage_vi: 'Uống 2 viên mỗi ngày',
    usage_zh: '每日服用2粒',
    price: 2800,
    image: 'https://images.unsplash.com/photo-1550572017-4414fac29c7c?w=400',
    category: 'supplements',
    disease: 'immunity',
    store: 'thailand',
    inStock: true,
    weight: 0.1,
    isSample: false
  },
  {
    id: '14',
    name: 'Кокосовое масло лечебное',
    name_en: 'Therapeutic Coconut Oil',
    name_vi: 'Dầu Dừa Trị Liệu',
    name_zh: '治疗椰子油',
    description: 'Органическое кокосовое масло для кожи и волос',
    description_en: 'Organic coconut oil for skin and hair',
    description_vi: 'Dầu dừa hữu cơ cho da và tóc',
    description_zh: '有机椰子油护肤护发',
    composition: 'Масло кокоса холодного отжима 100%',
    composition_en: 'Cold-pressed coconut oil 100%',
    composition_vi: 'Dầu dừa ép lạnh 100%',
    composition_zh: '冷榨椰子油100%',
    usage: 'Наносить на кожу и волосы, оставить на 20 минут',
    usage_en: 'Apply to skin and hair, leave for 20 minutes',
    usage_vi: 'Thoa lên da và tóc, để trong 20 phút',
    usage_zh: '涂抹于皮肤和头发，保持20分钟',
    price: 520,
    image: 'https://images.unsplash.com/photo-1474440692490-2e83ae13ba29?w=400',
    category: 'cosmetics',
    disease: 'skin_care',
    store: 'thailand',
    inStock: true,
    weight: 0.25,
    isSample: false
  },

  // Vietnam Store - Vietnamese medicines
  {
    id: '21',
    name: 'Вьетнамский бальзам Звезда',
    name_en: 'Vietnamese Golden Star Balm',
    name_vi: 'Cao Sao Vàng',
    name_zh: '越南金星膏',
    description: 'Классический вьетнамский бальзам от головной боли',
    description_en: 'Classic Vietnamese balm for headache relief',
    description_vi: 'Cao Việt Nam cổ điển giảm đau đầu',
    description_zh: '经典越南头痛药膏',
    composition: 'Камфора, ментол, эвкалиптовое масло',
    composition_en: 'Camphor, menthol, eucalyptus oil',
    composition_vi: 'Long não, bạc hà, dầu bạch đàn',
    composition_zh: '樟脑、薄荷醇、桉树油',
    usage: 'Втирать в виски при головной боли',
    usage_en: 'Massage into temples for headache',
    usage_vi: 'Xoa vào thái dương khi đau đầu',
    usage_zh: '头痛时按摩太阳穴',
    price: 250,
    image: 'https://images.unsplash.com/photo-1612831200409-d3cd0c6c9c9f?w=400',
    category: 'ointments',
    disease: 'headache',
    store: 'vietnam',
    inStock: true,
    weight: 0.04,
    isSample: false
  },
  {
    id: '22',
    name: 'Капсулы лотоса',
    name_en: 'Lotus Capsules',
    name_vi: 'Viên Sen',
    name_zh: '莲花胶囊',
    description: 'Капсулы из семян лотоса для успокоения нервной системы',
    description_en: 'Lotus seed capsules for calming nervous system',
    description_vi: 'Viên hạt sen an thần',
    description_zh: '莲子胶囊镇静神经',
    composition: 'Экстракт семян лотоса, магний',
    composition_en: 'Lotus seed extract, magnesium',
    composition_vi: 'Chiết xuất hạt sen, magie',
    composition_zh: '莲子提取物、镁',
    usage: 'Принимать 1-2 капсулы перед сном',
    usage_en: 'Take 1-2 capsules before bedtime',
    usage_vi: 'Uống 1-2 viên trước khi ngủ',
    usage_zh: '睡前服用1-2粒',
    price: 890,
    image: 'https://images.unsplash.com/photo-1628016041793-389e8265524f?w=400',
    category: 'supplements',
    disease: 'stress',
    store: 'vietnam',
    inStock: true,
    weight: 0.08,
    isSample: false
  },
  {
    id: '23',
    name: 'Масло кайепута',
    name_en: 'Cajeput Oil',
    name_vi: 'Dầu Tràm',
    name_zh: '白千层油',
    description: 'Эфирное масло для лечения простуды и мышечных болей',
    description_en: 'Essential oil for cold and muscle pain treatment',
    description_vi: 'Tinh dầu trị cảm lạnh và đau cơ',
    description_zh: '治疗感冒和肌肉疼痛的精油',
    composition: 'Эфирное масло кайепута 100%',
    composition_en: 'Cajeput essential oil 100%',
    composition_vi: 'Tinh dầu tràm 100%',
    composition_zh: '白千层精油100%',
    usage: 'Втирать в грудь и спину при простуде',
    usage_en: 'Massage into chest and back for cold',
    usage_vi: 'Xoa lên ngực và lưng khi cảm lạnh',
    usage_zh: '感冒时按摩胸部和背部',
    price: 420,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400',
    category: 'herbal_medicine',
    disease: 'cold',
    store: 'vietnam',
    inStock: true,
    weight: 0.05,
    isSample: false
  },
  {
    id: '24',
    name: 'Травяной чай от печени',
    name_en: 'Liver Detox Tea',
    name_vi: 'Trà Giải Độc Gan',
    name_zh: '护肝茶',
    description: 'Травяной чай для очищения и поддержки печени',
    description_en: 'Herbal tea for liver cleansing and support',
    description_vi: 'Trà thảo dược làm sạch và hỗ trợ gan',
    description_zh: '清肝护肝草药茶',
    composition: 'Расторопша, артишок, одуванчик',
    composition_en: 'Milk thistle, artichoke, dandelion',
    composition_vi: 'Kế sữa, atiso, bồ công anh',
    composition_zh: '水飞蓟、洋蓟、蒲公英',
    usage: 'Заваривать 1 пакетик на стакан кипятка 2 раза в день',
    usage_en: 'Brew 1 sachet per cup of boiling water twice daily',
    usage_vi: 'Pha 1 túi trên cốc nước sôi 2 lần mỗi ngày',
    usage_zh: '每日两次，每次1包冲泡开水',
    price: 680,
    image: 'https://images.unsplash.com/photo-1563822249366-3efaa8b9e2fc?w=400',
    category: 'herbal_medicine',
    disease: 'liver',
    store: 'vietnam',
    inStock: true,
    weight: 0.1,
    isSample: false
  }
];

export const getMockProducts = (): Product[] => {
  return mockProducts;
};

// Mock orders data for local development
export const mockOrders = [
  {
    id: 'order-1',
    orderNumber: '221001',
    userId: 'user-1',
    userEmail: 'test@example.com',
    store: 'china',
    items: [
      {
        productId: '1',
        name: 'Yunnan Baiyao',
        quantity: 2,
        price: 850
      }
    ],
    totalAmount: 1700,
    totalPrice: 1700,
    subtotal: 1700,
    status: 'processing',
    shippingMethod: 'standard',
    shippingAddress: {
      fullName: 'Тест Пользователь',
      phone: '+79001234567',
      address: 'ул. Тестовая, д. 1',
      city: 'Москва',
      country: 'Россия',
      postalCode: '123456'
    },
    paymentMethod: 'card',
    createdAt: new Date().toISOString(),
    orderDate: new Date().toISOString()
  },
  {
    id: 'order-2',
    orderNumber: '221002',
    userId: 'user-1',
    userEmail: 'test@example.com',
    store: 'thailand',
    items: [
      {
        productId: '11',
        name: 'Thai Herbal Balm',
        quantity: 1,
        price: 380
      }
    ],
    totalAmount: 380,
    totalPrice: 380,
    subtotal: 380,
    status: 'delivered',
    shippingMethod: 'express',
    shippingAddress: {
      fullName: 'Тест Пользователь',
      phone: '+79001234567',
      address: 'ул. Тестовая, д. 1',
      city: 'Москва',
      country: 'Россия',
      postalCode: '123456'
    },
    paymentMethod: 'card',
    trackingNumber: 'TRACK123456',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    orderDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()
  }
];

export const getMockOrders = () => {
  return mockOrders;
};
