import { Product } from '../contexts/CartContext';

// Mock products data for local development when Edge Function is not deployed
export const mockProducts: Product[] = [
  // Popular Products (shown on homepage by default) - China store
  {
    id: 'pop1',
    name: 'Бальзам Тигровый',
    name_en: 'Tiger Balm',
    name_vi: 'Cao Hổ',
    name_zh: '虎标万金油',
    description: 'Обезболивающий бальзам при мышечных и суставных болях',
    description_en: 'Pain relief balm for muscle and joint pain',
    description_vi: 'Dầu giảm đau cho đau cơ và khớp',
    description_zh: '缓解肌肉和关节疼痛的药膏',
    shortDescription: 'Обезболивающий бальзам при мышечных и суставных болях',
    shortDescription_en: 'Pain relief balm for muscle and joint pain',
    shortDescription_vi: 'Dầu giảm đau cho đau cơ và khớp',
    shortDescription_zh: '缓解肌肉和关节疼痛的药膏',
    composition: 'Камфора, ментол, гвоздичное масло',
    composition_en: 'Camphor, menthol, clove oil',
    composition_vi: 'Long não, bạc hà, dầu đinh hương',
    composition_zh: '樟脑、薄荷醇、丁香油',
    usage: 'Втирать в болезненные места 2-3 раза в день',
    usage_en: 'Massage into painful areas 2-3 times daily',
    usage_vi: 'Xoa bóp vào vùng đau 2-3 lần mỗi ngày',
    usage_zh: '每天按摩疼痛部位2-3次',
    price: 450,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400',
    category: 'ointments',
    disease: 'joints',
    diseaseCategories: ['popular', 'joints'],
    store: 'china',
    inStock: true,
    weight: 0.05,
    isSample: false
  },
  {
    id: 'pop2',
    name: 'Женьшень красный',
    name_en: 'Red Ginseng',
    name_vi: 'Nhân Sâm Đỏ',
    name_zh: '红参',
    description: 'Корень красного женьшеня для повышения энергии и иммунитета',
    description_en: 'Red ginseng root for energy and immunity boost',
    description_vi: 'Rễ nhân sâm đỏ tăng cường năng lượng và miễn dịch',
    description_zh: '红参根增强能量和免疫力',
    shortDescription: 'Корень красного женьшеня для повышения энергии и иммунитета',
    shortDescription_en: 'Red ginseng root for energy and immunity boost',
    shortDescription_vi: 'Rễ nhân sâm đỏ tăng cường năng lượng và miễn dịch',
    shortDescription_zh: '红参根增强能量和免疫力',
    composition: 'Корень красного женьшеня 100%',
    composition_en: 'Red ginseng root 100%',
    composition_vi: 'Rễ nhân sâm đỏ 100%',
    composition_zh: '红参根100%',
    usage: 'Принимать 1-2 капсулы в день во время еды',
    usage_en: 'Take 1-2 capsules daily with meals',
    usage_vi: 'Uống 1-2 viên mỗi ngày cùng bữa ăn',
    usage_zh: '每日随餐服用1-2粒',
    price: 3500,
    image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=400',
    category: 'pills',
    disease: 'heart',
    diseaseCategories: ['popular', 'heart'],
    store: 'china',
    inStock: true,
    weight: 0.2,
    isSample: false
  },
  {
    id: 'pop3',
    name: 'Жемчужный крем премиум',
    name_en: 'Premium Pearl Cream',
    name_vi: 'Kem Ngọc Trai Cao Cấp',
    name_zh: '高级珍珠膏',
    description: 'Увлажняющий крем с жемчужной пудрой для здоровой кожи',
    description_en: 'Moisturizing cream with pearl powder for healthy skin',
    description_vi: 'Kem dưỡng ẩm với bột ngọc trai cho làn da khỏe mạnh',
    description_zh: '含珍珠粉的保湿霜',
    shortDescription: 'Увлажняющий крем с жемчужной пудрой для здоровой кожи',
    shortDescription_en: 'Moisturizing cream with pearl powder for healthy skin',
    shortDescription_vi: 'Kem dưỡng ẩm với bột ngọc trai cho làn da khỏe mạnh',
    shortDescription_zh: '含珍珠粉的保湿霜',
    composition: 'Жемчужная пудра, коллаген, витамин E',
    composition_en: 'Pearl powder, collagen, vitamin E',
    composition_vi: 'Bột ngọc trai, collagen, vitamin E',
    composition_zh: '珍珠粉、胶原蛋白、维生素E',
    usage: 'Наносить на чистую кожу лица утром и вечером',
    usage_en: 'Apply to clean facial skin morning and evening',
    usage_vi: 'Thoa lên da mặt sạch buổi sáng và tối',
    usage_zh: '早晚涂抹于洁净面部',
    price: 1200,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400',
    category: 'cosmetics',
    disease: 'skin',
    diseaseCategories: ['popular', 'skin'],
    store: 'china',
    inStock: true,
    weight: 0.15,
    isSample: false
  },
  {
    id: 'pop4',
    name: 'Пластырь обезболивающий',
    name_en: 'Pain Relief Patch',
    name_vi: 'Miếng Dán Giảm Đau',
    name_zh: '止痛贴',
    description: 'Лечебный пластырь для снятия боли в мышцах и суставах',
    description_en: 'Therapeutic patch for muscle and joint pain relief',
    description_vi: 'Miếng dán trị liệu giảm đau cơ và khớp',
    description_zh: '缓解肌肉和关节疼痛的治疗贴',
    shortDescription: 'Лечебный пластырь для снятия боли в мышцах и суставах',
    shortDescription_en: 'Therapeutic patch for muscle and joint pain relief',
    shortDescription_vi: 'Miếng dán trị liệu giảm đau cơ và khớp',
    shortDescription_zh: '缓解肌肉和关节疼痛的治疗贴',
    composition: 'Экстракт перца, ментол, камфора',
    composition_en: 'Pepper extract, menthol, camphor',
    composition_vi: 'Chiết xuất ớt, bạc hà, long não',
    composition_zh: '辣椒提取物、薄荷醇、樟脑',
    usage: 'Наклеить на болезненную область на 8-12 часов',
    usage_en: 'Apply to painful area for 8-12 hours',
    usage_vi: 'Dán lên vùng đau trong 8-12 giờ',
    usage_zh: '贴在疼痛部位8-12小时',
    price: 550,
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
    category: 'patches',
    disease: 'joints',
    diseaseCategories: ['popular', 'joints'],
    store: 'china',
    inStock: true,
    weight: 0.08,
    isSample: false
  },
  {
    id: 'pop5',
    name: 'Эликсир молодости',
    name_en: 'Youth Elixir',
    name_vi: 'Tiên Dược Trẻ Hóa',
    name_zh: '青春灵药',
    description: 'Травяной эликсир для укрепления здоровья и долголетия',
    description_en: 'Herbal elixir for health and longevity',
    description_vi: 'Tiên dược thảo mộc tăng cường sức khỏe và tuổi thọ',
    description_zh: '增强健康和长寿的草药灵药',
    shortDescription: 'Травяной эликсир для укрепления здоровья и долголетия',
    shortDescription_en: 'Herbal elixir for health and longevity',
    shortDescription_vi: 'Tiên dược thảo mộc tăng cường sức khỏe và tuổi thọ',
    shortDescription_zh: '增强健康和长寿的草药灵药',
    composition: 'Женьшень, дереза, лимонник',
    composition_en: 'Ginseng, goji berry, schisandra',
    composition_vi: 'Nhân sâm, kỷ tử, ngũ vị tử',
    composition_zh: '人参、枸杞、五味子',
    usage: 'Принимать по 10 мл 2 раза в день',
    usage_en: 'Take 10ml twice daily',
    usage_vi: 'Uống 10ml 2 lần mỗi ngày',
    usage_zh: '每日两次，每次10毫升',
    price: 2800,
    image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=400',
    category: 'elixirs',
    disease: 'heart',
    diseaseCategories: ['popular', 'heart'],
    store: 'china',
    inStock: true,
    weight: 0.25,
    isSample: false
  },
  {
    id: 'pop6',
    name: 'Капли для глаз с хризантемой',
    name_en: 'Chrysanthemum Eye Drops',
    name_vi: 'Thuốc Nhỏ Mắt Cúc Hoa',
    name_zh: '菊花滴眼液',
    description: 'Натуральные капли для снятия усталости глаз',
    description_en: 'Natural drops for eye fatigue relief',
    description_vi: 'Thuốc nhỏ tự nhiên giảm mỏi mắt',
    description_zh: '天然滴眼液缓解眼疲劳',
    shortDescription: 'Натуральные капли для снятия усталости глаз',
    shortDescription_en: 'Natural drops for eye fatigue relief',
    shortDescription_vi: 'Thuốc nhỏ tự nhiên giảm mỏi mắt',
    shortDescription_zh: '天然滴眼液缓解眼疲劳',
    composition: 'Экстракт хризантемы, витамин А',
    composition_en: 'Chrysanthemum extract, vitamin A',
    composition_vi: 'Chiết xuất hoa cúc, vitamin A',
    composition_zh: '菊花提取物、维生素A',
    usage: 'Закапывать по 1-2 капли 3 раза в день',
    usage_en: 'Instill 1-2 drops 3 times daily',
    usage_vi: 'Nhỏ 1-2 giọt 3 lần mỗi ngày',
    usage_zh: '每日3次，每次1-2滴',
    price: 680,
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
    category: 'sprays',
    disease: 'vision',
    diseaseCategories: ['popular', 'vision'],
    store: 'china',
    inStock: true,
    weight: 0.03,
    isSample: false
  },
  
  // China Store - Traditional medicines
  {
    id: '1',
    name: '云南白药',
    name_en: 'Yunnan Baiyao',
    name_vi: 'Vân Nam Bạch Dược',
    name_zh: '云南白药',
    description: 'Традиционное китайское средство для остановки кровотечений и заживления ран',
    description_en: 'Traditional Chinese medicine for stopping bleeding and wound healing',
    description_vi: 'Thuốc cổ truyền Trung Quốc để cầm máu và chữa lành vết thương',
    description_zh: '传统中药止血愈伤药',
    shortDescription: 'Традиционное китайское средство для остановки кровотечений',
    shortDescription_en: 'Traditional Chinese medicine for bleeding',
    shortDescription_vi: 'Thuốc cổ truyền để cầm máu',
    shortDescription_zh: '传统中药止血药',
    composition: 'Корень белой травы, камфора, экстракты трав',
    composition_en: 'White herb root, camphor, herbal extracts',
    composition_vi: 'Rễ cỏ trắng, long não, chiết xuất thảo dược',
    composition_zh: '白药根、樟脑、草药提取物',
    usage: 'Наносить на пораженную область 2-3 раза в день',
    usage_en: 'Apply to affected area 2-3 times daily',
    usage_vi: 'Bôi lên vùng bị ảnh hưởng 2-3 lần mỗi ngày',
    usage_zh: '每天涂抹患处2-3次',
    price: 850,
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
    category: 'ointments',
    disease: 'skin',
    diseaseCategories: ['skin'],
    store: 'china',
    inStock: true,
    weight: 0.1,
    isSample: false
  },
  {
    id: '2',
    name: 'Жемчужный крем',
    name_en: 'Pearl Cream',
    name_vi: 'Kem Ngọc Trai',
    name_zh: '珍珠膏',
    description: 'Увлажняющий крем с жемчужной пудрой для здоровой кожи',
    description_en: 'Moisturizing cream with pearl powder for healthy skin',
    description_vi: 'Kem dưỡng ẩm với bột ngọc trai cho làn da khỏe mạnh',
    description_zh: '含珍珠粉的保湿霜',
    shortDescription: 'Увлажняющий крем с жемчужной пудрой',
    shortDescription_en: 'Moisturizing cream with pearl powder',
    shortDescription_vi: 'Kem dưỡng ẩm với bột ngọc trai',
    shortDescription_zh: '含珍珠粉的保湿霜',
    composition: 'Жемчужная пудра, коллаген, витамин E',
    composition_en: 'Pearl powder, collagen, vitamin E',
    composition_vi: 'Bột ngọc trai, collagen, vitamin E',
    composition_zh: '珍珠粉、胶原蛋白、维生素E',
    usage: 'Наносить на чистую кожу лица утром и вечером',
    usage_en: 'Apply to clean facial skin morning and evening',
    usage_vi: 'Thoa lên da mặt sạch buổi sáng và tối',
    usage_zh: '早晚涂抹于洁净面部',
    price: 1200,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400',
    category: 'cosmetics',
    disease: 'skin',
    diseaseCategories: ['skin'],
    store: 'china',
    inStock: true,
    weight: 0.15,
    isSample: false
  },
  {
    id: '3',
    name: 'Чай лечебный',
    name_en: 'Herbal Tea',
    name_vi: 'Trà Thảo Dược',
    name_zh: '草药茶',
    description: 'Лечебный чай для улучшения пищеварения',
    description_en: 'Herbal tea for improved digestion',
    description_vi: 'Trà thảo dược cải thiện tiêu hóa',
    description_zh: '改善消化的草药茶',
    shortDescription: 'Лечебный чай для улучшения пищеварения',
    shortDescription_en: 'Herbal tea for improved digestion',
    shortDescription_vi: 'Trà thảo dược cải thiện tiêu hóa',
    shortDescription_zh: '改善消化的草药茶',
    composition: 'Зеленый чай, женьшень, имбирь',
    composition_en: 'Green tea, ginseng, ginger',
    composition_vi: 'Trà xanh, nhân sâm, gừng',
    composition_zh: '绿茶、人参、生姜',
    usage: 'Заваривать 1 пакетик на стакан горячей воды',
    usage_en: 'Brew 1 bag per cup of hot water',
    usage_vi: 'Pha 1 túi cho một cốc nước nóng',
    usage_zh: '用一袋冲泡一杯热水',
    price: 680,
    image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=400',
    category: 'teas',
    disease: 'digestive',
    diseaseCategories: ['digestive'],
    store: 'china',
    inStock: true,
    weight: 0.2,
    isSample: false
  },
  {
    id: '4',
    name: 'Капсулы для печени',
    name_en: 'Liver Capsules',
    name_vi: 'Viên Nang Gan',
    name_zh: '护肝胶囊',
    description: 'Капсулы для защиты и восстановления печени',
    description_en: 'Capsules for liver protection and recovery',
    description_vi: 'Viên nang bảo vệ và phục hồi gan',
    description_zh: '保护和恢复肝脏的胶囊',
    shortDescription: 'Капсулы для защиты и восстановления печени',
    shortDescription_en: 'Capsules for liver protection',
    shortDescription_vi: 'Viên nang bảo vệ gan',
    shortDescription_zh: '保护肝脏的胶囊',
    composition: 'Экстракт расторопши, артишок',
    composition_en: 'Milk thistle extract, artichoke',
    composition_vi: 'Chiết xuất cây kế sữa, atisô',
    composition_zh: '奶蓟提取物、朝鲜蓟',
    usage: 'Принимать 1-2 капсулы 2 раза в день',
    usage_en: 'Take 1-2 capsules twice daily',
    usage_vi: 'Uống 1-2 viên 2 lần mỗi ngày',
    usage_zh: '每天服用1-2粒，每日两次',
    price: 1850,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400',
    category: 'pills',
    disease: 'liver',
    diseaseCategories: ['liver'],
    store: 'china',
    inStock: true,
    weight: 0.05,
    isSample: false
  },
  {
    id: '5',
    name: 'Пробник - Женьшень',
    name_en: 'Sample - Ginseng',
    name_vi: 'Mẫu thử - Nhân Sâm',
    name_zh: '试用装 - 人参',
    description: 'Пробная упаковка женьшеня (10г)',
    description_en: 'Ginseng sample pack (10g)',
    description_vi: 'Gói mẫu nhân sâm (10g)',
    description_zh: '人参试用装（10克）',
    shortDescription: 'Пробная упаковка женьшеня (10г)',
    shortDescription_en: 'Ginseng sample pack (10g)',
    shortDescription_vi: 'Gói mẫu nhân sâm (10g)',
    shortDescription_zh: '人参试用装（10克）',
    composition: 'Корень красного женьшеня 100%',
    composition_en: 'Red ginseng root 100%',
    composition_vi: 'Rễ nhân sâm đỏ 100%',
    composition_zh: '红参根100%',
    usage: 'Заварить и пить как чай',
    usage_en: 'Brew and drink as tea',
    usage_vi: 'Pha và uống như trà',
    usage_zh: '冲泡饮用',
    price: 200,
    image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=400',
    category: 'samples',
    disease: 'heart',
    diseaseCategories: ['heart'],
    store: 'china',
    inStock: true,
    weight: 0.01,
    isSample: true
  },

  // Popular Products - Thailand store
  {
    id: 'pop_th1',
    name: 'Тайский зеленый бальзам',
    name_en: 'Thai Green Balm',
    name_vi: 'Dầu Xanh Thái',
    name_zh: '泰国绿色膏',
    description: 'Травяной бальзам для облегчения головной боли и простуды',
    description_en: 'Herbal balm for headache and cold relief',
    description_vi: 'Dầu thảo dược giảm đau đầu và cảm lạnh',
    description_zh: '草药膏缓解头痛和感冒',
    shortDescription: 'Травяной бальзам для облегчения головной боли и простуды',
    shortDescription_en: 'Herbal balm for headache and cold relief',
    shortDescription_vi: 'Dầu thảo dược giảm đau đầu và cảm lạnh',
    shortDescription_zh: '草药膏缓解头痛和感冒',
    composition: 'Ментол, эвкалипт, мята',
    composition_en: 'Menthol, eucalyptus, mint',
    composition_vi: 'Bạc hà, bạch đàn, húng',
    composition_zh: '薄荷醇、桉树、薄荷',
    usage: 'Наносить на виски и переносицу',
    usage_en: 'Apply to temples and bridge of nose',
    usage_vi: 'Thoa lên thái dương và sống mũi',
    usage_zh: '涂抹在太阳穴和鼻梁',
    price: 380,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400',
    category: 'ointments',
    disease: 'headache',
    diseaseCategories: ['popular', 'headache', 'cold'],
    store: 'thailand',
    inStock: true,
    weight: 0.05,
    isSample: false
  },
  {
    id: 'pop_th2',
    name: 'Тайский масляный ингалятор',
    name_en: 'Thai Oil Inhaler',
    name_vi: 'Dầu Hít Thái',
    name_zh: '泰国吸入器',
    description: 'Ингалятор с эфирными маслами от насморка',
    description_en: 'Essential oil inhaler for nasal congestion',
    description_vi: 'Dầu hít tinh dầu trị nghẹt mũi',
    description_zh: '精油吸入器治疗鼻塞',
    shortDescription: 'Ингалятор с эфирными маслами от насморка',
    shortDescription_en: 'Essential oil inhaler for nasal congestion',
    shortDescription_vi: 'Dầu hít tinh dầu trị nghẹt mũi',
    shortDescription_zh: '精油吸入器治疗鼻塞',
    composition: 'Эвкалипт, мята, камфора',
    composition_en: 'Eucalyptus, mint, camphor',
    composition_vi: 'Bạch đàn, bạc hà, long não',
    composition_zh: '桉树、薄荷、樟脑',
    usage: 'Вдыхать при заложенности носа',
    usage_en: 'Inhale when nose is congested',
    usage_vi: 'Hít khi bị nghẹt mũi',
    usage_zh: '鼻塞时吸入',
    price: 250,
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=400',
    category: 'sprays',
    disease: 'cold',
    diseaseCategories: ['popular', 'cold'],
    store: 'thailand',
    inStock: true,
    weight: 0.02,
    isSample: false
  },
  {
    id: 'pop_th3',
    name: 'Капсулы с куркумой тайские',
    name_en: 'Thai Turmeric Capsules',
    name_vi: 'Viên Nghệ Thái',
    name_zh: '泰国姜黄胶囊',
    description: 'Тайские капсулы с куркумой для иммунитета',
    description_en: 'Thai turmeric capsules for immunity',
    description_vi: 'Viên nghệ Thái tăng miễn dịch',
    description_zh: '泰国姜黄胶囊增强免疫',
    shortDescription: 'Тайские капсулы с куркумой для иммунитета',
    shortDescription_en: 'Thai turmeric capsules for immunity',
    shortDescription_vi: 'Viên nghệ Thái tăng miễn dịch',
    shortDescription_zh: '泰国姜黄胶囊增强免疫',
    composition: 'Куркума, имбирь, черный перец',
    composition_en: 'Turmeric, ginger, black pepper',
    composition_vi: 'Nghệ, gừng, tiêu đen',
    composition_zh: '姜黄、生姜、黑胡椒',
    usage: 'Принимать 1-2 капсулы в день',
    usage_en: 'Take 1-2 capsules daily',
    usage_vi: 'Uống 1-2 viên mỗi ngày',
    usage_zh: '每日1-2粒',
    price: 620,
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=400',
    category: 'pills',
    disease: 'digestive',
    diseaseCategories: ['popular', 'digestive'],
    store: 'thailand',
    inStock: true,
    weight: 0.06,
    isSample: false
  },
  {
    id: 'pop_th4',
    name: 'Тайский массажный бальзам',
    name_en: 'Thai Massage Balm',
    name_vi: 'Dầu Massage Thái',
    name_zh: '泰式按摩膏',
    description: 'Разогревающий бальзам для массажа',
    description_en: 'Warming balm for massage',
    description_vi: 'Dầu ấm để massage',
    description_zh: '按摩用温热膏',
    shortDescription: 'Разогревающий бальзам для массажа',
    shortDescription_en: 'Warming balm for massage',
    shortDescription_vi: 'Dầu ấm để massage',
    shortDescription_zh: '按摩用温热膏',
    composition: 'Имбирь, галангал, лемонграсс',
    composition_en: 'Ginger, galangal, lemongrass',
    composition_vi: 'Gừng, riềng, sả',
    composition_zh: '生姜、高良姜、柠檬草',
    usage: 'Втирать массажными движениями',
    usage_en: 'Massage into skin',
    usage_vi: 'Xoa bóp vào da',
    usage_zh: '按摩涂抹',
    price: 480,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400',
    category: 'ointments',
    disease: 'joints',
    diseaseCategories: ['popular', 'joints'],
    store: 'thailand',
    inStock: true,
    weight: 0.1,
    isSample: false
  },

  // Thailand Store - Thai traditional medicines
  {
    id: '11',
    name: 'Тайский бальзам',
    name_en: 'Thai Herbal Balm',
    name_vi: 'Dầu Thảo Dược Thái',
    name_zh: '泰国草药膏',
    description: 'Травяной бальзам для облегчения головной боли и простуды',
    description_en: 'Herbal balm for headache and cold relief',
    description_vi: 'Dầu thảo dược giảm đau đầu và cảm lạnh',
    description_zh: '缓解头痛和感冒的草药膏',
    shortDescription: 'Травяной бальзам для головной боли',
    shortDescription_en: 'Herbal balm for headache',
    shortDescription_vi: 'Dầu thảo dược giảm đau đầu',
    shortDescription_zh: '缓解头痛的草药膏',
    composition: 'Лемонграсс, эвкалипт, мята, борнеол',
    composition_en: 'Lemongrass, eucalyptus, mint, borneol',
    composition_vi: 'Sả, bạch đàn, bạc hà, borneol',
    composition_zh: '柠檬草、桉树、薄荷、冰片',
    usage: 'Наносить на виски и затылок при головной боли',
    usage_en: 'Apply to temples and back of head for headache',
    usage_vi: 'Thoa lên thái dương và gáy khi đau đầu',
    usage_zh: '头痛时涂抹于太阳穴和后颈',
    price: 380,
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=400',
    category: 'ointments',
    disease: 'headache',
    diseaseCategories: ['headache', 'cold'],
    store: 'thailand',
    inStock: true,
    weight: 0.08,
    isSample: false
  },
  {
    id: '12',
    name: 'Мангостиновая паста',
    name_en: 'Mangosteen Paste',
    name_vi: 'Thuốc Măng Cụt',
    name_zh: '山竹膏',
    description: 'Натуральная паста из мангостина для пищеварения',
    description_en: 'Natural mangosteen paste for digestion',
    description_vi: 'Thuốc dán măng cụt tự nhiên cho tiêu hóa',
    description_zh: '天然山竹膏助消化',
    shortDescription: 'Натуральная паста из мангостина',
    shortDescription_en: 'Natural mangosteen paste',
    shortDescription_vi: 'Thuốc dán măng cụt tự nhiên',
    shortDescription_zh: '天然山竹膏',
    composition: 'Экстракт мангостина, мед, травы',
    composition_en: 'Mangosteen extract, honey, herbs',
    composition_vi: 'Chiết xuất măng cụt, mật ong, thảo dược',
    composition_zh: '山竹提取物、蜂蜜、草药',
    usage: 'Принимать 1 чайную ложку 3 раза в день',
    usage_en: 'Take 1 teaspoon 3 times daily',
    usage_vi: 'Uống 1 thìa cà phê 3 lần mỗi ngày',
    usage_zh: '每日3次，每次1茶匙',
    price: 650,
    image: 'https://images.unsplash.com/photo-1584308972272-9e4e7685e80f?w=400',
    category: 'elixirs',
    disease: 'digestive',
    diseaseCategories: ['digestive'],
    store: 'thailand',
    inStock: true,
    weight: 0.12,
    isSample: false
  },
  {
    id: '13',
    name: 'Капсулы из кордицепса',
    name_en: 'Cordyceps Capsules',
    name_vi: 'Viên Đông Trùng Hạ Thảo',
    name_zh: '冬虫夏草胶囊',
    description: 'Капсулы кордицепса для энергии и выносливости',
    description_en: 'Cordyceps capsules for energy and endurance',
    description_vi: 'Viên đông trùng hạ thảo tăng năng lượng',
    description_zh: '冬虫夏草胶囊增强能量',
    shortDescription: 'Капсулы кордицепса для энергии',
    shortDescription_en: 'Cordyceps capsules for energy',
    shortDescription_vi: 'Viên đông trùng hạ thảo',
    shortDescription_zh: '冬虫夏草胶囊',
    composition: 'Экстракт кордицепса 500мг',
    composition_en: 'Cordyceps extract 500mg',
    composition_vi: 'Chiết xuất đông trùng hạ thảo 500mg',
    composition_zh: '冬虫夏草提取物500毫克',
    usage: 'Принимать 2 капсулы в день',
    usage_en: 'Take 2 capsules daily',
    usage_vi: 'Uống 2 viên mỗi ngày',
    usage_zh: '每日服用2粒',
    price: 2800,
    image: 'https://images.unsplash.com/photo-1550572017-4414fac29c7c?w=400',
    category: 'pills',
    disease: 'heart',
    diseaseCategories: ['heart'],
    store: 'thailand',
    inStock: true,
    weight: 0.1,
    isSample: false
  },
  {
    id: '14',
    name: 'Кокосовое масло лечебное',
    name_en: 'Therapeutic Coconut Oil',
    name_vi: 'Dầu Dừa Trị Liệu',
    name_zh: '治疗椰子油',
    description: 'Органическое кокосовое масло для кожи и волос',
    description_en: 'Organic coconut oil for skin and hair',
    description_vi: 'Dầu dừa hữu cơ cho da và tóc',
    description_zh: '有机椰子油护肤护发',
    shortDescription: 'Органическое кокосовое масло для кожи',
    shortDescription_en: 'Organic coconut oil for skin',
    shortDescription_vi: 'Dầu dừa hữu cơ cho da',
    shortDescription_zh: '有机椰子油护肤',
    composition: 'Масло кокоса холодного отжима 100%',
    composition_en: 'Cold-pressed coconut oil 100%',
    composition_vi: 'Dầu dừa ép lạnh 100%',
    composition_zh: '冷榨椰子油100%',
    usage: 'Наносить на кожу и волосы, оставить на 20 минут',
    usage_en: 'Apply to skin and hair, leave for 20 minutes',
    usage_vi: 'Thoa lên da và tóc, để trong 20 phút',
    usage_zh: '涂抹于皮肤和头发，保持20分钟',
    price: 520,
    image: 'https://images.unsplash.com/photo-1474440692490-2e83ae13ba29?w=400',
    category: 'cosmetics',
    disease: 'skin',
    diseaseCategories: ['skin'],
    store: 'thailand',
    inStock: true,
    weight: 0.25,
    isSample: false
  },

  // Popular Products - Vietnam store
  {
    id: 'pop_vn1',
    name: 'Вьетнамская звёздочка',
    name_en: 'Vietnamese Star Balm',
    name_vi: 'Cao Sao Vàng',
    name_zh: '越南金星膏',
    description: 'Классический вьетнамский бальзам от простуды и головной боли',
    description_en: 'Classic Vietnamese balm for cold and headache',
    description_vi: 'Cao truyền thống Việt Nam trị cảm lạnh và đau đầu',
    description_zh: '经典越南药膏治疗感冒和头痛',
    shortDescription: 'Классический вьетнамский бальзам от простуды и головной боли',
    shortDescription_en: 'Classic Vietnamese balm for cold and headache',
    shortDescription_vi: 'Cao truyền thống Việt Nam trị cảm lạnh và đau đầu',
    shortDescription_zh: '经典越南药膏治疗感冒和头痛',
    composition: 'Ментол, камфора, гвоздичное масло, эвкалипт',
    composition_en: 'Menthol, camphor, clove oil, eucalyptus',
    composition_vi: 'Bạc hà, long não, dầu đinh hương, bạch đàn',
    composition_zh: '薄荷醇、樟脑、丁香油、桉树',
    usage: 'Втирать в виски, грудь, спину',
    usage_en: 'Massage into temples, chest, back',
    usage_vi: 'Xoa bóp vào thái dương, ngực, lưng',
    usage_zh: '按摩太阳穴、胸部、背部',
    price: 290,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400',
    category: 'ointments',
    disease: 'cold',
    diseaseCategories: ['popular', 'cold', 'headache'],
    store: 'vietnam',
    inStock: true,
    weight: 0.04,
    isSample: false
  },
  {
    id: 'pop_vn2',
    name: 'Капсулы с куркумой',
    name_en: 'Turmeric Capsules',
    name_vi: 'Viên Nghệ',
    name_zh: '姜黄胶囊',
    description: 'Капсулы с экстрактом куркумы для иммунитета',
    description_en: 'Turmeric extract capsules for immunity',
    description_vi: 'Viên chiết xuất nghệ tăng miễn dịch',
    description_zh: '姜黄提取物胶囊增强免疫力',
    shortDescription: 'Капсулы с экстрактом куркумы для иммунитета',
    shortDescription_en: 'Turmeric extract capsules for immunity',
    shortDescription_vi: 'Viên chiết xuất nghệ tăng miễn dịch',
    shortDescription_zh: '姜黄提取物胶囊增强免疫力',
    composition: 'Экстракт куркумы, витамин С',
    composition_en: 'Turmeric extract, vitamin C',
    composition_vi: 'Chiết xuất nghệ, vitamin C',
    composition_zh: '姜黄提取物、维生素C',
    usage: 'Принимать 1 капсулу 2 раза в день',
    usage_en: 'Take 1 capsule twice daily',
    usage_vi: 'Uống 1 viên 2 lần mỗi ngày',
    usage_zh: '每日两次，每次1粒',
    price: 750,
    image: 'https://images.unsplash.com/photo-1628016041793-389e8265524f?w=400',
    category: 'pills',
    disease: 'heart',
    diseaseCategories: ['popular', 'heart'],
    store: 'vietnam',
    inStock: true,
    weight: 0.06,
    isSample: false
  },
  {
    id: 'pop_vn3',
    name: 'Вьетнамский чай с лотосом',
    name_en: 'Vietnamese Lotus Tea',
    name_vi: 'Trà Sen Việt',
    name_zh: '越南莲花茶',
    description: 'Успокаивающий чай с цветами лотоса',
    description_en: 'Calming tea with lotus flowers',
    description_vi: 'Trà an thần với hoa sen',
    description_zh: '莲花镇静茶',
    shortDescription: 'Успокаивающий чай с цветами лотоса',
    shortDescription_en: 'Calming tea with lotus flowers',
    shortDescription_vi: 'Trà an thần với hoa sen',
    shortDescription_zh: '莲花镇静茶',
    composition: 'Цветы лотоса, зеленый чай, жасмин',
    composition_en: 'Lotus flowers, green tea, jasmine',
    composition_vi: 'Hoa sen, trà xanh, hoa nhài',
    composition_zh: '莲花、绿茶、茉莉花',
    usage: 'Заваривать 1 пакетик на чашку',
    usage_en: 'Brew 1 bag per cup',
    usage_vi: 'Pha 1 túi cho 1 cốc',
    usage_zh: '每杯冲泡1袋',
    price: 450,
    image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=400',
    category: 'teas',
    disease: 'nervous',
    diseaseCategories: ['popular', 'nervous'],
    store: 'vietnam',
    inStock: true,
    weight: 0.05,
    isSample: false
  },
  {
    id: 'pop_vn4',
    name: 'Вьетнамское масло от комаров',
    name_en: 'Vietnamese Mosquito Oil',
    name_vi: 'Dầu Đuổi Muỗi Việt',
    name_zh: '越南驱蚊油',
    description: 'Натуральное масло для защиты от насекомых',
    description_en: 'Natural oil for insect protection',
    description_vi: 'Dầu tự nhiên chống côn trùng',
    description_zh: '天然驱虫油',
    shortDescription: 'Натуральное масло для защиты от насекомых',
    shortDescription_en: 'Natural oil for insect protection',
    shortDescription_vi: 'Dầu tự nhiên chống côn trùng',
    shortDescription_zh: '天然驱虫油',
    composition: 'Цитронелла, эвкалипт, мята',
    composition_en: 'Citronella, eucalyptus, mint',
    composition_vi: 'Sả chanh, bạch đàn, bạc hà',
    composition_zh: '香茅、桉树、薄荷',
    usage: 'Наносить на кожу или одежду',
    usage_en: 'Apply to skin or clothing',
    usage_vi: 'Thoa lên da hoặc quần áo',
    usage_zh: '涂抹在皮肤或衣服上',
    price: 320,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400',
    category: 'cosmetics',
    disease: 'skin',
    diseaseCategories: ['popular', 'skin'],
    store: 'vietnam',
    inStock: true,
    weight: 0.05,
    isSample: false
  },

  // Vietnam Store - Vietnamese medicines
  {
    id: '21',
    name: 'Вьетнамский бальзам Звезда премиум',
    name_en: 'Vietnamese Golden Star Balm Premium',
    name_vi: 'Cao Sao Vàng Cao Cấp',
    name_zh: '越南金星膏高级版',
    description: 'Премиум версия классического вьетнамского бальзама',
    description_en: 'Premium version of classic Vietnamese balm',
    description_vi: 'Phiên bản cao cấp của cao Việt Nam cổ điển',
    description_zh: '经典越南药膏高级版',
    shortDescription: 'Премиум версия вьетнамского бальзама',
    shortDescription_en: 'Premium Vietnamese balm',
    shortDescription_vi: 'Phiên bản cao cấp',
    shortDescription_zh: '高级版药膏',
    composition: 'Камфора, ментол, эвкалиптовое масло',
    composition_en: 'Camphor, menthol, eucalyptus oil',
    composition_vi: 'Long não, bạc hà, dầu bạch đàn',
    composition_zh: '樟脑、薄荷醇、桉树油',
    usage: 'Втирать в виски при головной боли',
    usage_en: 'Massage into temples for headache',
    usage_vi: 'Xoa vào thái dương khi đau đầu',
    usage_zh: '头痛时按摩太阳穴',
    price: 350,
    image: 'https://images.unsplash.com/photo-1612831200409-d3cd0c6c9c9f?w=400',
    category: 'ointments',
    disease: 'headache',
    diseaseCategories: ['headache', 'cold'],
    store: 'vietnam',
    inStock: true,
    weight: 0.04,
    isSample: false
  },
  {
    id: '22',
    name: 'Капсулы лотоса',
    name_en: 'Lotus Capsules',
    name_vi: 'Viên Sen',
    name_zh: '莲花胶囊',
    description: 'Капсулы из семян лотоса для успокоения нервной системы',
    description_en: 'Lotus seed capsules for calming nervous system',
    description_vi: 'Viên hạt sen an thần',
    description_zh: '莲子胶囊镇静神经',
    shortDescription: 'Капсулы из семян лотоса для успокоения',
    shortDescription_en: 'Lotus seed capsules for calming',
    shortDescription_vi: 'Viên hạt sen an thần',
    shortDescription_zh: '莲子胶囊镇静',
    composition: 'Экстракт семян лотоса, магний',
    composition_en: 'Lotus seed extract, magnesium',
    composition_vi: 'Chiết xuất hạt sen, magie',
    composition_zh: '莲子提取物、镁',
    usage: 'Принимать 1-2 капсулы перед сном',
    usage_en: 'Take 1-2 capsules before bedtime',
    usage_vi: 'Uống 1-2 viên trước khi ngủ',
    usage_zh: '睡前服用1-2粒',
    price: 890,
    image: 'https://images.unsplash.com/photo-1628016041793-389e8265524f?w=400',
    category: 'pills',
    disease: 'nervous',
    diseaseCategories: ['nervous'],
    store: 'vietnam',
    inStock: true,
    weight: 0.08,
    isSample: false
  },
  {
    id: '23',
    name: 'Масло кайепута',
    name_en: 'Cajeput Oil',
    name_vi: 'Dầu Tràm',
    name_zh: '白千层油',
    description: 'Эфирное масло для лечения простуды и мышечных болей',
    description_en: 'Essential oil for cold and muscle pain treatment',
    description_vi: 'Tinh dầu trị cảm lạnh và đau cơ',
    description_zh: '治疗感冒和肌肉疼痛的精油',
    shortDescription: 'Эфирное масло от простуды',
    shortDescription_en: 'Essential oil for cold',
    shortDescription_vi: 'Tinh dầu trị cảm lạnh',
    shortDescription_zh: '治疗感冒的精油',
    composition: 'Эфирное масло кайепута 100%',
    composition_en: 'Cajeput essential oil 100%',
    composition_vi: 'Tinh dầu tràm 100%',
    composition_zh: '白千层精油100%',
    usage: 'Втирать в грудь и спину при простуде',
    usage_en: 'Massage into chest and back for cold',
    usage_vi: 'Xoa lên ngực và lưng khi cảm lạnh',
    usage_zh: '感冒时按摩胸部和背部',
    price: 420,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400',
    category: 'cosmetics',
    disease: 'cold',
    diseaseCategories: ['cold', 'joints'],
    store: 'vietnam',
    inStock: true,
    weight: 0.05,
    isSample: false
  },
  {
    id: '24',
    name: 'Травяной чай от печени',
    name_en: 'Liver Detox Tea',
    name_vi: 'Trà Giải Độc Gan',
    name_zh: '护肝茶',
    description: 'Травяной чай для очищения и поддержки печени',
    description_en: 'Herbal tea for liver cleansing and support',
    description_vi: 'Trà thảo dược làm sạch và hỗ trợ gan',
    description_zh: '清肝护肝草药茶',
    shortDescription: 'Травяной чай для печени',
    shortDescription_en: 'Herbal tea for liver',
    shortDescription_vi: 'Trà thảo dược cho gan',
    shortDescription_zh: '护肝草药茶',
    composition: 'Расторопша, артишок, одуванчик',
    composition_en: 'Milk thistle, artichoke, dandelion',
    composition_vi: 'Kế sữa, atiso, bồ công anh',
    composition_zh: '水飞蓟、洋蓟、蒲公英',
    usage: 'Заваривать 1 пакетик на стакан кипятка 2 раза в день',
    usage_en: 'Brew 1 sachet per cup of boiling water twice daily',
    usage_vi: 'Pha 1 túi trên cốc nước sôi 2 lần mỗi ngày',
    usage_zh: '每日两次，每次1包冲泡开水',
    price: 680,
    image: 'https://images.unsplash.com/photo-1563822249366-3efaa8b9e2fc?w=400',
    category: 'teas',
    disease: 'liver',
    diseaseCategories: ['liver'],
    store: 'vietnam',
    inStock: true,
    weight: 0.1,
    isSample: false
  }
];

export const getMockProducts = (): Product[] => {
  return mockProducts;
};

// Mock orders data for local development
export const mockOrders = [
  {
    id: 'order-1',
    orderNumber: '221001',
    userId: 'user-1',
    userEmail: 'test@example.com',
    store: 'china',
    items: [
      {
        productId: '1',
        name: 'Yunnan Baiyao',
        quantity: 2,
        price: 850
      }
    ],
    totalAmount: 1700,
    totalPrice: 1700,
    subtotal: 1700,
    status: 'processing',
    shippingMethod: 'standard',
    shippingAddress: {
      fullName: 'Тест Пользователь',
      phone: '+79001234567',
      address: 'ул. Тестовая, д. 1',
      city: 'Москва',
      country: 'Россия',
      postalCode: '123456'
    },
    paymentMethod: 'card',
    createdAt: new Date().toISOString(),
    orderDate: new Date().toISOString()
  },
  {
    id: 'order-2',
    orderNumber: '221002',
    userId: 'user-1',
    userEmail: 'test@example.com',
    store: 'thailand',
    items: [
      {
        productId: '11',
        name: 'Thai Herbal Balm',
        quantity: 1,
        price: 380
      }
    ],
    totalAmount: 380,
    totalPrice: 380,
    subtotal: 380,
    status: 'delivered',
    shippingMethod: 'express',
    shippingAddress: {
      fullName: 'Тест Пользователь',
      phone: '+79001234567',
      address: 'ул. Тестовая, д. 1',
      city: 'Москва',
      country: 'Россия',
      postalCode: '123456'
    },
    paymentMethod: 'card',
    trackingNumber: 'TRACK123456',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    orderDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()
  }
];

export const getMockOrders = () => {
  return mockOrders;
};
